package io.github.opletter.css2kobweb

internal val cssRules = mapOf(
    ":any-link" to "anyLink",
    ":link" to "link",
    ":target" to "target",
    ":visited" to "visited",
    ":hover" to "hover",
    ":active" to "active",
    ":focus" to "focus",
    ":focus-visible" to "focusVisible",
    ":autofill" to "autofill",
    ":enabled" to "enabled",
    ":disabled" to "disabled",
    ":read-only" to "readOnly",
    ":read-write" to "readWrite",
    ":placeholder-shown" to "placeholderShown",
    ":default" to "default",
    ":checked" to "checked",
    ":indeterminate" to "indeterminate",
    ":valid" to "valid",
    ":invalid" to "invalid",
    ":in-range" to "inRange",
    ":out-of-range" to "outOfRange",
    ":required" to "required",
    ":optional" to "optional",
    ":user-invalid" to "userInvalid",
    ":root" to "root",
    ":empty" to "empty",
    ":first-child" to "firstChild",
    ":last-child" to "lastChild",
    ":only-child" to "onlyChild",
    ":first-of-type" to "firstOfType",
    ":last-of-type" to "lastOfType",
    ":only-of-type" to "onlyOfType",
    // support both single and double colon
    "::before" to "before",
    ":before" to "before",
    "::after" to "after",
    ":after" to "after",
    "::selection" to "selection",
    ":selection" to "selection",
    "::first-letter" to "firstLetter",
    ":first-letter" to "firstLetter",
    "::first-line" to "firstLine",
    ":first-line" to "firstLine",
)